version: '1.0.0'
# postgres db

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

# string: "postgres://postgres:postgres@localhost:5432/postgres"